version: '3.7'
services:
  db:
    container_name: db
    image: postgres
    restart: always
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      - DOCKER=True
      - POSTGRES_USER=user1
      - POSTGRES_PASSWORD=password1
      - POSTGRES_DB=fastapi
    ports:
      - 5432:5432

  api:
    container_name: api
    build: .
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - 8080:8080


  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./pgadmin:/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"

volumes:
  postgres_volume:


