version: '3.7'
services:

  api:
    container_name: api
    build: .
    volumes:
      - .:/app
    ports:
      - 8081:8080

  redis:
    container_name: redis
    image: redis
    ports:
      - 6378:6379
    
  redisinsight:
    depends_on:
      - redis
    image: redislabs/redisinsight:latest
    ports:
      - '8001:8001'