"""fixed table messages

Revision ID: 019d59fe5767
Revises: c0ba29cfe2cf
Create Date: 2023-05-20 20:24:24.177743

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '019d59fe5767'
down_revision = 'c0ba29cfe2cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('content', sa.Text(), nullable=True))
    op.add_column('messages', sa.Column('date_time', sa.DateTime(), nullable=True))
    op.drop_column('messages', 'context')
    op.drop_column('messages', 'datetime')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('context', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('messages', 'date_time')
    op.drop_column('messages', 'content')
    # ### end Alembic commands ###
