"""fixed models

Revision ID: 2ba36621392b
Revises: 0eaf8aef2cdf
Create Date: 2023-05-18 17:11:12.931803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ba36621392b'
down_revision = '0eaf8aef2cdf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chats_unique_name', table_name='chats')
    op.drop_column('chats', 'unique_name')
    op.add_column('messages', sa.Column('context', sa.Text(), nullable=True))
    op.add_column('messages', sa.Column('datetime', sa.DateTime(), nullable=True))
    op.alter_column('userchat', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userchat', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('messages', 'datetime')
    op.drop_column('messages', 'context')
    op.add_column('chats', sa.Column('unique_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_chats_unique_name', 'chats', ['unique_name'], unique=False)
    # ### end Alembic commands ###
