"""redis id field

Revision ID: c0ba29cfe2cf
Revises: 2ba36621392b
Create Date: 2023-05-18 17:13:36.746117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0ba29cfe2cf'
down_revision = '2ba36621392b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('redis_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'redis_id')
    # ### end Alembic commands ###
